import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Posts from '../public/components/posts'
import { useEffect } from 'react'
import { useDispatch} from 'react-redux'
import { AppDispatch } from '../public/redux/store'
import axios from 'axios'

import { GetPostsFail,GetPostsRequest,GetPostsSuccess } from '../public/redux/posts/actions'
const Home: NextPage = () => {
  
  const dispatch:AppDispatch=useDispatch()
const getPosts=()=>{
  
  return async(dispatch:AppDispatch)=>{
    dispatch(GetPostsRequest())
    try{ 
         const response=await axios.get('https://jsonplaceholder.typicode.com/posts')
         console.log(response.data)
       dispatch(GetPostsSuccess(response.data))
    }
    catch(er:any){
        console.log(er.message)
        dispatch(GetPostsFail(er.message))
    }
}
}
useEffect(()=>{
dispatch(getPosts());
},[])
  


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

   
     
<Posts/>
</>
    
  )
}

export default Home
